---
# tasks file for gradle

- name: Download Gradle
  get_url:
    url: "https://services.gradle.org/distributions/gradle-{{ gradle_version }}-bin.zip"
    dest: "/tmp/gradle-{{ gradle_version }}-bin.zip"

- name: Unarchive the compressed Gradle binaries
  unarchive:
    copy: false
    src: "/tmp/gradle-{{ gradle_version }}-bin.zip"
    dest: /usr/local
    creates: "/usr/local/gradle-{{ gradle_version }}"
  tags: gradle

- name: Update the symbolic link to the Gradle install
  file:
    path: /usr/local/gradle
    src: "/usr/local/gradle-{{ gradle_version }}"
    state: link
    force: true
  tags: gradle

- name: Add Gradle bin to PATH
  file:
    dest: /usr/local/bin/gradle
    src: "/usr/local/gradle/bin/gradle"
    state: link
    mode: 0755
    force: true
  tags: gradle

- name: Set GRADLE_HOME environment variable
  lineinfile:
    dest: /etc/environment
    regexp: '^GRADLE_HOME.*'
    line: 'GRADLE_HOME=/usr/local/gradle'
    insertbefore: '^PATH.*'
  tags: gradle
