# This playbook gathers cross-account VPC facts because the security group for qlstg loy-int-nginx-integration needs to
# allow traffic from qldev, qlsit, qlstg accounts, lsl, old, qbr VPCs.
---

- name: Assume role for qldev account
  sts_assume_role:
    region: "{{ aws_region }}"
    role_arn: "arn:aws:iam::{{ aws_accounts_new.qldev.account_id }}:role/assumed-ansible"
    role_session_name: qldev_assumed_role
  register: qldev_assumed_role
  when: use_sts
  tags:
    - always

- name: Assume role for qlsit account
  sts_assume_role:
    region: "{{ aws_region }}"
    role_arn: "arn:aws:iam::{{ aws_accounts_new.qlsit.account_id }}:role/assumed-ansible"
    role_session_name: qlsit_assumed_role
  register: qlsit_assumed_role
  when: use_sts
  tags:
    - always

- name: Get VPC subnet facts for lsl-dev
  ec2_vpc_subnet_facts:
    aws_access_key: "{{ qldev_assumed_role.sts_creds.access_key }}"
    aws_secret_key: "{{ qldev_assumed_role.sts_creds.secret_key }}"
    security_token: "{{ qldev_assumed_role.sts_creds.session_token }}"
    region: "{{ aws_region }}"
    filters:
      "tag:Channel": "lsl"
      "tag:Env": "dev"
      "tag:Type": "protected"
  register: lsl_dev_vpc_protected_subnet_fact

- name: Get VPC subnet facts for lsl-sit
  ec2_vpc_subnet_facts:
    aws_access_key: "{{ qlsit_assumed_role.sts_creds.access_key }}"
    aws_secret_key: "{{ qlsit_assumed_role.sts_creds.secret_key }}"
    security_token: "{{ qlsit_assumed_role.sts_creds.session_token }}"
    region: "{{ aws_region }}"
    filters:
      "tag:Channel": "lsl"
      "tag:Env": "sit"
      "tag:Type": "protected"
  register: lsl_sit_vpc_protected_subnet_fact

- name: Get VPC subnet facts for qbr-dev
  ec2_vpc_subnet_facts:
    aws_access_key: "{{ qldev_assumed_role.sts_creds.access_key }}"
    aws_secret_key: "{{ qldev_assumed_role.sts_creds.secret_key }}"
    security_token: "{{ qldev_assumed_role.sts_creds.session_token }}"
    region: "{{ aws_region }}"
    filters:
      "tag:Channel": "qbr"
      "tag:Env": "dev"
      "tag:Type": "protected"
  register: qbr_dev_vpc_protected_subnet_fact

- name: Get VPC subnet facts for qbr-sit
  ec2_vpc_subnet_facts:
    aws_access_key: "{{ qlsit_assumed_role.sts_creds.access_key }}"
    aws_secret_key: "{{ qlsit_assumed_role.sts_creds.secret_key }}"
    security_token: "{{ qlsit_assumed_role.sts_creds.session_token }}"
    region: "{{ aws_region }}"
    filters:
      "tag:Channel": "qbr"
      "tag:Env": "sit"
      "tag:Type": "protected"
  register: qbr_sit_vpc_protected_subnet_fact

- name: Get VPC subnet facts for old-dev
  ec2_vpc_subnet_facts:
    aws_access_key: "{{ qldev_assumed_role.sts_creds.access_key }}"
    aws_secret_key: "{{ qldev_assumed_role.sts_creds.secret_key }}"
    security_token: "{{ qldev_assumed_role.sts_creds.session_token }}"
    region: "{{ aws_region }}"
    filters:
      "tag:Channel": "old"
      "tag:Env": "dev"
      "tag:Type": "protected"
  register: old_dev_vpc_protected_subnet_fact

- name: Get VPC subnet facts for old-sit
  ec2_vpc_subnet_facts:
    aws_access_key: "{{ qlsit_assumed_role.sts_creds.access_key }}"
    aws_secret_key: "{{ qlsit_assumed_role.sts_creds.secret_key }}"
    security_token: "{{ qlsit_assumed_role.sts_creds.session_token }}"
    region: "{{ aws_region }}"
    filters:
      "tag:Channel": "old"
      "tag:Env": "sit"
      "tag:Type": "protected"
  register: old_sit_vpc_protected_subnet_fact
