---
asg_desired_size: 1
asg_min_size: 1
asg_max_size: 4
sec_group_instance_rules:
  - proto: tcp
    from_port: 32768
    to_port: 60999
    cidr_ip: "{{ vpc_fact.vpcs.0.cidr_block }}"
    rule_desc: "Allow traffic to ECS dynamic port range from {{ channel }} VPC"

datadog_tags:
  - DatadogEnabled: true  # leave Datadog running on these instances
