---
asg_desired_size: 4
asg_min_size: 4
instance_type: m4.xlarge

sec_group_instance_rules:
  - proto: tcp
    from_port: 32768
    to_port: 60999
    cidr_ip: "{{ vpc_fact.vpcs.0.cidr_block }}"
    rule_desc: "Allow traffic to ECS dynamic port range from {{ channel }} VPC"
  - proto: tcp
    from_port: 7800
    to_port: 7804
    group_name: "sec-{{ infrastructure_name }}"
    rule_desc: "Allow JGROUP cluster traffic within the protected subnet"

user_data: |
  #!/bin/bash

  export PATH=$PATH:/usr/local/bin

  echo "ECS_CLUSTER=cluster-{{ channel }}-{{ env }}-{{ deploy_in_subnet }}-{{ cluster_id }}" >> /etc/ecs/ecs.config
  echo "ECS_AVAILABLE_LOGGING_DRIVERS=[\"splunk\",\"syslog\",\"fluentd\",\"json-file\"]" >> /etc/ecs/ecs.config
  echo "ECS_ENABLE_CONTAINER_METADATA=true" >> /etc/ecs/ecs.config

  # Make mount point directory
  mkdir -p /mnt/efs-epq-hybris

  # Look up EFS file system ID by name
  efs_id=$(aws efs describe-file-systems --region {{ aws_region }} |
           jq -r '.FileSystems[] | select(.Name == "nfs-{{ channel }}-{{ env }}-hybris") | .FileSystemId')

  # Add nfs mount to fstab
  # https://docs.aws.amazon.com/efs/latest/ug/mount-fs-auto-mount-onreboot.html
  echo "${efs_id}:/ /mnt/efs-epq-hybris efs defaults,_netdev 0 0" >> /etc/fstab

  # Mount
  mount -a

  # Create directories for different containers
  mkdir -p /mnt/efs-epq-hybris/data
  mkdir -p /mnt/efs-epq-hybris/solr
