---
# tasks file for fa_infra_ansible destruction

### Get vars

- name: Get vars for environment
  include:
    ../../../get_env_vars.yml
  tags:
    - always

### ec2 instances

- name: Get instances
  ec2_remote_facts:
    region: "{{ aws_region }}"
    filters:
      "tag:Env": "{{ env }}"
      "tag:Type": "{{ type }}"
  register: ec2

- name: ec2 instances terminatation
  ec2:
    region: "{{ aws_region }}"
    instance_ids: "{{ item.id }}"
    state: absent
    wait: true
    wait_timeout: 300
  register: ec2
  with_items:
    ec2.instances

### Security Group

- name: Security group for instance
  ec2_group:
    region: "{{ aws_region }}"
    name: "sec-{{ env }}-{{ type }}"
    description: "Security group for {{ type }} ec2 instances"
    state: absent
  tags:
    - sec_group

### IAM role and policy

- name: IAM policy
  iam_policy:
    iam_type: role
    iam_name: "{{ env }}-{{ type }}"
    policy_name: "policy-{{ env }}-{{ type }}"
    state: absent
  tags:
    - iam

- name: IAM role
  iam:
    iam_type: role
    name: "{{ env }}-{{ type }}"
    state: absent
  tags:
    - iam
