---
cluster_id: jenkins-slave
asg_desired_size: 2
asg_min_size: 2
instance_type: m5.large
sec_group_instance_rules:
  - proto: tcp
    from_port: 32768
    to_port: 60999
    cidr_ip: "{{ vpc_fact_cidr_block }}"
