---
asg_desired_size: 2
asg_min_size: 1
asg_max_size: 3
instance_type: t2.medium
sec_group_instance_rules:
  - proto: tcp
    from_port: 8080
    to_port: 8080
    cidr_ip: "{{ vpc_fact.vpcs.0.cidr_block }}"
  - proto: tcp
    from_port: 11751
    to_port: 11751
    cidr_ip: "{{ vpc_fact.vpcs.0.cidr_block }}"
