---
asg_desired_size: "{{ 42 if env == 'prd' or env == 'stg' else 28 }}"
asg_max_size: "{{ asg_desired_size|int + 10 }}"
sec_group_instance_rules:
  - proto: tcp
    from_port: 32768
    to_port: 60999
    cidr_ip: "{{ vpc_fact.vpcs.0.cidr_block }}"
    rule_desc: "Allow traffic to ECS dynamic port range from {{ channel }} VPC"
  - proto: tcp
    from_port: 32768
    to_port: 60999
    cidr_ip: "172.19.0.0/16"
    rule_desc: "Allow traffic to ECS dynamic port range from the IP account"
