---
extra_tags:
  - EBSToUse: "vol-03f01eea703a1dcf2"  # EBS for certbot in loy VPC

user_data: |
  #!/bin/bash

  echo "ECS_CLUSTER=cluster-{{ channel }}-{{ env }}-{{ deploy_in_subnet }}-{{ cluster_id }}" >> /etc/ecs/ecs.config
  echo "ECS_AVAILABLE_LOGGING_DRIVERS=[\"splunk\",\"syslog\",\"fluentd\",\"json-file\"]" >> /etc/ecs/ecs.config
  echo "ECS_ENABLE_CONTAINER_METADATA=true" >> /etc/ecs/ecs.config

  export PATH=$PATH:/usr/local/bin
  export AWS_DEFAULT_REGION="ap-southeast-2"

  # Get the current instance id
  instance_id=$(curl -s http://169.254.169.254/latest/meta-data/instance-id)

  # Get the instance tags
  describe_tags_result=$(aws ec2 describe-tags --filters "Name=resource-id,Values=${instance_id}")

  # Get values of specific tags
  ecs_cluster_name=$(echo ${describe_tags_result} | jq -r '.Tags[] | select(.Key == "EcsClusterName") | .Value')
  ENV=$(echo ${describe_tags_result} | jq -r '.Tags[] | select(.Key == "Env") | .Value')

  # Install NFS client
  yum -y install nfs-utils

  # Make mount point directory
  mkdir -p {{ efs_mount_point.stackstorm }}
  mkdir -p {{ ebs_mount_point.certbot }}
  mkdir -p {{ efs_mount_point.sonarqube }}

  # Add certbot ebs volumes to fstab
  echo "/dev/sdf {{ ebs_mount_point.certbot }} auto defaults 0 0 " >> /etc/fstab

  # Add nfs mount to fstab
  echo "{{ efs_dns.stackstorm }}:/ {{ efs_mount_point.stackstorm }} nfs4
        nfsvers=4.1,rsize=1048576,wsize=1048576,hard,timeo=600,retrans=2,_netdev 0 0" >> /etc/fstab

  # Add sonar nfs mount to fstab
  echo "{{ efs_dns.sonarqube }}:/ {{ efs_mount_point.sonarqube }} nfs4
        nfsvers=4.1,rsize=1048576,wsize=1048576,hard,timeo=600,retrans=2,_netdev 0 0" >> /etc/fstab

  # Mount
  mount -a

  # These permissions are required for sonar docker container to write content
  chown -R 999:995 {{ efs_mount_point.sonarqube }}

  # This ES config is required for sonarqube docker ref: https://github.com/SonarSource/docker-sonarqube/issues/279
  sysctl -w vm.max_map_count=262144
